import { db } from './src/lib/firebase-node';
import { collection, doc, setDoc, getDocs } from 'firebase/firestore';

interface EventInput {
  academicYear: string;
  programme: string;
  regulation: string;
  semester: string;
  startDate: string; // YYYY-MM-DD
  endDate: string; // YYYY-MM-DD
  title: string;
  description: string;
  category: string;
  workingDay: string; // "Yes" or "No"
  holiday: string; // "Yes" or "No"
  applicableTo: string;
  status: string; // "Published"
  remarks?: string;
}

function generateDeterministicEventId(event: any) {
  const academicYear = (event.academicYear || '').trim().toLowerCase();
  const normalizedTitle = (event.title || '')
    .trim()
    .toLowerCase()
    .replace(/\s+/g, ' ');
  const startDate = (event.startDate || '').trim().toLowerCase();
  const endDate = (event.endDate || event.startDate || '').trim().toLowerCase();
  const programme = (event.programme || '').trim().toLowerCase();
  const semester = (event.semester || '').trim().toLowerCase();
  const category = (event.category || '').trim().toLowerCase();

  const rawKey = `${academicYear}_${normalizedTitle}_${startDate}_${endDate}_${programme}_${semester}_${category}`;
  
  const safeId = rawKey
    .replace(/[^a-zA-Z0-9_\-]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
  
  return `cal-${safeId}`.substring(0, 120).toLowerCase();
}

const pdfEvents: EventInput[] = [
  // ==================== HOLIDAYS (2026 - 2027) ====================
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2026-06-26",
    endDate: "2026-06-26",
    title: "Moharram Holiday",
    description: "Official religious holiday observation for Moharram.",
    category: "Holiday",
    workingDay: "No",
    holiday: "Yes",
    applicableTo: "All Students and Faculty",
    status: "Published",
    remarks: "Religious Holiday"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2026-08-15",
    endDate: "2026-08-15",
    title: "Independence Day",
    description: "National festival and flag hoisting ceremony.",
    category: "Holiday",
    workingDay: "No",
    holiday: "Yes",
    applicableTo: "All Students and Faculty",
    status: "Published",
    remarks: "National Holiday"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2026-08-26",
    endDate: "2026-08-26",
    title: "Milad-un-Nabi",
    description: "Official religious holiday observation.",
    category: "Holiday",
    workingDay: "No",
    holiday: "Yes",
    applicableTo: "All Students and Faculty",
    status: "Published",
    remarks: "Religious Holiday"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2026-09-04",
    endDate: "2026-09-04",
    title: "Sri Krishna Jayanthi",
    description: "Official religious holiday observation.",
    category: "Holiday",
    workingDay: "No",
    holiday: "Yes",
    applicableTo: "All Students and Faculty",
    status: "Published",
    remarks: "Religious Holiday"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2026-09-14",
    endDate: "2026-09-14",
    title: "Vinayakar Chathurthi",
    description: "Official religious holiday observation.",
    category: "Holiday",
    workingDay: "No",
    holiday: "Yes",
    applicableTo: "All Students and Faculty",
    status: "Published",
    remarks: "Religious Holiday"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2026-10-02",
    endDate: "2026-10-02",
    title: "Gandhi Jayanthi Holiday",
    description: "National holiday observation.",
    category: "Holiday",
    workingDay: "No",
    holiday: "Yes",
    applicableTo: "All Students and Faculty",
    status: "Published",
    remarks: "National Holiday"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2026-10-19",
    endDate: "2026-10-19",
    title: "Ayudha Pooja Holiday",
    description: "Official religious holiday observation.",
    category: "Holiday",
    workingDay: "No",
    holiday: "Yes",
    applicableTo: "All Students and Faculty",
    status: "Published",
    remarks: "Official Holiday"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2026-10-20",
    endDate: "2026-10-20",
    title: "Vijaya Dasami Holiday",
    description: "Official religious holiday observation.",
    category: "Holiday",
    workingDay: "No",
    holiday: "Yes",
    applicableTo: "All Students and Faculty",
    status: "Published",
    remarks: "Official Holiday"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2026-11-08",
    endDate: "2026-11-08",
    title: "Deepavali Holiday",
    description: "Official religious holiday observation.",
    category: "Holiday",
    workingDay: "No",
    holiday: "Yes",
    applicableTo: "All Students and Faculty",
    status: "Published",
    remarks: "Official Holiday"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2026-12-25",
    endDate: "2026-12-25",
    title: "Christmas Holiday",
    description: "Official religious holiday observation.",
    category: "Holiday",
    workingDay: "No",
    holiday: "Yes",
    applicableTo: "All Students and Faculty",
    status: "Published",
    remarks: "Official Holiday"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2027-01-01",
    endDate: "2027-01-01",
    title: "New Year Holiday",
    description: "Official holiday observation.",
    category: "Holiday",
    workingDay: "No",
    holiday: "Yes",
    applicableTo: "All Students and Faculty",
    status: "Published",
    remarks: "Official Holiday"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2027-01-14",
    endDate: "2027-01-14",
    title: "Pongal Holiday",
    description: "State festival holiday observation.",
    category: "Holiday",
    workingDay: "No",
    holiday: "Yes",
    applicableTo: "All Students and Faculty",
    status: "Published",
    remarks: "State Festival"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2027-01-15",
    endDate: "2027-01-15",
    title: "Thiruvalluvar Day Holiday",
    description: "State holiday observation.",
    category: "Holiday",
    workingDay: "No",
    holiday: "Yes",
    applicableTo: "All Students and Faculty",
    status: "Published",
    remarks: "State Holiday"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2027-01-16",
    endDate: "2027-01-16",
    title: "Uzhavar Thirunal Holiday",
    description: "State holiday observation.",
    category: "Holiday",
    workingDay: "No",
    holiday: "Yes",
    applicableTo: "All Students and Faculty",
    status: "Published",
    remarks: "State Holiday"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2027-01-26",
    endDate: "2027-01-26",
    title: "Republic Day Holiday",
    description: "National festival and parade ceremony.",
    category: "Holiday",
    workingDay: "No",
    holiday: "Yes",
    applicableTo: "All Students and Faculty",
    status: "Published",
    remarks: "National Holiday"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2027-02-09",
    endDate: "2027-02-09",
    title: "Telugu New Year Holiday",
    description: "Official festival holiday.",
    category: "Holiday",
    workingDay: "No",
    holiday: "Yes",
    applicableTo: "All Students and Faculty",
    status: "Published",
    remarks: "Official Holiday"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2027-03-08",
    endDate: "2027-03-08",
    title: "Ramzan Holiday",
    description: "Official religious holiday observation.",
    category: "Holiday",
    workingDay: "No",
    holiday: "Yes",
    applicableTo: "All Students and Faculty",
    status: "Published",
    remarks: "Official Holiday"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2027-03-24",
    endDate: "2027-03-24",
    title: "Mahavir Jayanthi Holiday",
    description: "Official religious holiday observation.",
    category: "Holiday",
    workingDay: "No",
    holiday: "Yes",
    applicableTo: "All Students and Faculty",
    status: "Published",
    remarks: "Official Holiday"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2027-03-26",
    endDate: "2027-03-26",
    title: "Good Friday Holiday",
    description: "Official religious holiday observation.",
    category: "Holiday",
    workingDay: "No",
    holiday: "Yes",
    applicableTo: "All Students and Faculty",
    status: "Published",
    remarks: "Official Holiday"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2027-04-14",
    endDate: "2027-04-14",
    title: "Tamil New Year Holiday",
    description: "State holiday observation.",
    category: "Holiday",
    workingDay: "No",
    holiday: "Yes",
    applicableTo: "All Students and Faculty",
    status: "Published",
    remarks: "Official Holiday"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2027-05-01",
    endDate: "2027-05-01",
    title: "May Day Holiday",
    description: "Labour Day holiday.",
    category: "Holiday",
    workingDay: "No",
    holiday: "Yes",
    applicableTo: "All Students and Faculty",
    status: "Published",
    remarks: "Official Holiday"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2027-05-15",
    endDate: "2027-05-15",
    title: "Bakrid Holiday",
    description: "Official religious holiday.",
    category: "Holiday",
    workingDay: "No",
    holiday: "Yes",
    applicableTo: "All Students and Faculty",
    status: "Published",
    remarks: "Official Holiday"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2027-06-05",
    endDate: "2027-06-05",
    title: "Moharram Holiday",
    description: "Official religious holiday.",
    category: "Holiday",
    workingDay: "No",
    holiday: "Yes",
    applicableTo: "All Students and Faculty",
    status: "Published",
    remarks: "Official Holiday"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2027-08-15",
    endDate: "2027-08-15",
    title: "Independence Day Holiday",
    description: "National festival holiday.",
    category: "Holiday",
    workingDay: "No",
    holiday: "Yes",
    applicableTo: "All Students and Faculty",
    status: "Published",
    remarks: "National Holiday"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2027-08-16",
    endDate: "2027-08-16",
    title: "Milad-Un-Nabi Holiday",
    description: "Religious holiday observation.",
    category: "Holiday",
    workingDay: "No",
    holiday: "Yes",
    applicableTo: "All Students and Faculty",
    status: "Published",
    remarks: "Official Holiday"
  },

  // ==================== EVENTS CALENDAR (2026 - 2027) ====================
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2026-06-19",
    endDate: "2026-06-19",
    title: "Alumni Lecture-01",
    description: "Interactive session by prominent alumni sharing professional insights.",
    category: "Guest Lecture",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "B.Pharm & Pharm.D Students",
    status: "Published",
    remarks: "Placement Cell series"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2026-06-21",
    endDate: "2026-06-21",
    title: "International Yoga Day",
    description: "Institutional awareness and collective yoga practices for wellness.",
    category: "General Academic Event",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "All Students and Faculty",
    status: "Published",
    remarks: "Wellness Club"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2026-06-26",
    endDate: "2026-06-26",
    title: "International Day Against Drug Abuse and Illegal Trafficking",
    description: "Awareness drive and seminar organized by pharmaceutical student chapters.",
    category: "General Academic Event",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "All Students and Staff",
    status: "Published",
    remarks: "Youth Red Cross"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2026-07-20",
    endDate: "2026-07-24",
    title: "Faculty Development Programmes (FDPs) on Mental Health and Wellness",
    description: "5-day intensive training for educators on mindfulness and coping strategies.",
    category: "FDP",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "All Faculty Members",
    status: "Published",
    remarks: "Education Enhancement Cell"
  },
  {
    academicYear: "2026-2027",
    programme: "M.Pharm",
    regulation: "PCI 2020",
    semester: "All",
    startDate: "2026-07-22",
    endDate: "2026-07-22",
    title: "Career Guidance Programme-01 M. Pharm",
    description: "Specialized post-grad counseling regarding formulations and analytics R&D.",
    category: "Seminar",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "M.Pharm Students",
    status: "Published",
    remarks: "Placement Cell"
  },
  {
    academicYear: "2026-2027",
    programme: "Pharm.D",
    regulation: "PCI 2008",
    semester: "All",
    startDate: "2026-07-22",
    endDate: "2026-07-22",
    title: "Career Guidance Programme-02 Pharm. D",
    description: "Counseling regarding global residencies, pharmacotherapy, and clinical trials.",
    category: "Seminar",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "Pharm.D Students",
    status: "Published",
    remarks: "Placement Cell"
  },
  {
    academicYear: "2026-2027",
    programme: "B.Pharm",
    regulation: "PCI 2017",
    semester: "All",
    startDate: "2026-07-23",
    endDate: "2026-07-23",
    title: "Career Guidance Programme-03 B.Pharm",
    description: "Undergraduate guidance regarding sales, production, and high-degree options.",
    category: "Seminar",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "B.Pharm Students",
    status: "Published",
    remarks: "Placement Cell"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2026-07-24",
    endDate: "2026-07-24",
    title: "Talk on Entrepreneurship",
    description: "Expert webinar on ideation, fundraising, and incubating health-tech startups.",
    category: "Guest Lecture",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "All Students and Scholars",
    status: "Published",
    remarks: "Innovation Cell"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2026-07-29",
    endDate: "2026-07-29",
    title: "Continuing Pharmacy Education -01",
    description: "Academic reinforcement module for updating latest professional parameters.",
    category: "Seminar",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "B.Pharm & Pharm.D Students",
    status: "Published",
    remarks: "CPE Committee"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2026-07-29",
    endDate: "2026-07-29",
    title: "Gender Sensitivity Programme -01",
    description: "Empowerment seminar clarifying institutional equity and safety charters.",
    category: "General Academic Event",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "All Students and Staff",
    status: "Published",
    remarks: "ICC Cell"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2026-07-01",
    endDate: "2026-07-07",
    title: "Van Mahotsav",
    description: "Eco club sapling plantation drive and sustainable campus week.",
    category: "General Academic Event",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "All Students and Faculty",
    status: "Published",
    remarks: "Eco Club"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2026-08-01",
    endDate: "2026-08-07",
    title: "World Breastfeeding week",
    description: "Awareness poster exhibits, street acts, and clinical lectures.",
    category: "General Academic Event",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "Pharm.D and Nursing Students",
    status: "Published",
    remarks: "Community Health Service"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2026-08-05",
    endDate: "2026-08-05",
    title: "Continuing Pharmacy Education - 02",
    description: "Clinical updates and modern formulation technologies.",
    category: "Seminar",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "All Students and Faculty",
    status: "Published",
    remarks: "CPE Committee"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2026-08-05",
    endDate: "2026-08-05",
    title: "Internal Committee Programme -01",
    description: "Orientation of internal committee compliance mechanisms.",
    category: "General Academic Event",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "All Students",
    status: "Published",
    remarks: "ICC Cell"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2026-08-10",
    endDate: "2026-08-10",
    title: "Alumni Lecture -02",
    description: "Guest talk by industrial regulatory affairs team lead.",
    category: "Guest Lecture",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "All B.Pharm & M.Pharm Students",
    status: "Published",
    remarks: "Placement Cell Series"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2026-08-20",
    endDate: "2026-08-21",
    title: "National Conference on Frontiers in Drug Discovery-Medicinal Chemist's Perspective",
    description: "National Level Conference centering target mapping and molecular dynamics.",
    category: "Conference",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "All Students, Research Scholars & Faculty",
    status: "Published",
    remarks: "Chemistry Dept Initiative"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2026-09-02",
    endDate: "2026-09-02",
    title: "One day workshop on 3D Printing Technology for Pharmaceutical Research",
    description: "Hands-on formulation workshop with rapid-prototyping 3D printers.",
    category: "Workshop",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "B.Pharm & Pharm.D Final Years",
    status: "Published",
    remarks: "Skill Training Cell"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2026-09-11",
    endDate: "2026-09-11",
    title: "One-Day Workshop on \"Start-up Opportunities in Herbal and Phytopharmaceutical Sector\"",
    description: "Interactive session with Ayur-tech business incubators.",
    category: "Workshop",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "All Students",
    status: "Published",
    remarks: "EDC Cell"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2026-09-17",
    endDate: "2026-09-23",
    title: "National Pharmacovigilance Week",
    description: "Awareness walks, clinical audits, and safety reporting protocols.",
    category: "Seminar",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "All Students and Faculty",
    status: "Published",
    remarks: "Pharmacovigilance Committee"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2026-09-19",
    endDate: "2026-09-19",
    title: "Workshop on Bioanalytical Method Development and Validation, including BA, BE Studies",
    description: "Technical training on mass spectrometry, HPLC, and clinical pharmacokinetics.",
    category: "Workshop",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "M.Pharm & Research Scholars",
    status: "Published",
    remarks: "Analytical Division"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2026-09-25",
    endDate: "2026-09-25",
    title: "World Pharmacist Day Celebration",
    description: "Flag hoisting, professional oath-taking, and healthcare campaigns.",
    category: "General Academic Event",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "All Students and Faculty",
    status: "Published",
    remarks: "Pharmacy Club"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2026-09-13",
    endDate: "2026-09-13",
    title: "World First Aid Day",
    description: "Standard training regarding life support and clinical emergencies.",
    category: "General Academic Event",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "All Students",
    status: "Published",
    remarks: "Red Cross Chapter"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2026-09-24",
    endDate: "2026-09-24",
    title: "NSS Day- Blood Donation Camp",
    description: "Voluntary donation camp in coordination with Government Hospital Blood Bank.",
    category: "General Academic Event",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "All Students and Staff",
    status: "Published",
    remarks: "NSS Unit"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2026-10-09",
    endDate: "2026-10-09",
    title: "Talk on Incubation and Startup",
    description: "Insights regarding state subsidies, patents, and seed funds.",
    category: "Guest Lecture",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "All Students and Scholars",
    status: "Published",
    remarks: "IPR / Innovation Cell"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2026-10-09",
    endDate: "2026-10-09",
    title: "National cGMP Day Celebration - 2026",
    description: "Seminars on quality management, guidelines, and cleanroom design.",
    category: "General Academic Event",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "All B.Pharm & M.Pharm Students",
    status: "Published",
    remarks: "Pharmaceutics Division"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2026-10-12",
    endDate: "2026-10-12",
    title: "World Arthritis Day",
    description: "Geriatric medicine camps, diagnostic support, and clinical discussions.",
    category: "General Academic Event",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "Pharm.D Students",
    status: "Published",
    remarks: "Hospital Pharmacy Dept"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2026-10-26",
    endDate: "2026-10-26",
    title: "Alumni Lecture 03",
    description: "Expert tips on cracking competitive tests (GPAT / NIPER).",
    category: "Guest Lecture",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "B.Pharm Students",
    status: "Published",
    remarks: "Alumni Association"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2026-10-01",
    endDate: "2026-10-31",
    title: "World Breast Cancer Awareness Month",
    description: "Monthly breast health counseling and screening seminars.",
    category: "General Academic Event",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "All Female Students and Faculty",
    status: "Published",
    remarks: "Women Empowerment Cell"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2026-11-05",
    endDate: "2026-11-05",
    title: "Continuing Pharmacy Education - 03",
    description: "Focus on modern therapeutic models and biologics.",
    category: "Seminar",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "B.Pharm & Pharm.D Students",
    status: "Published",
    remarks: "CPE Committee"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2026-11-14",
    endDate: "2026-11-14",
    title: "World Diabetes Day",
    description: "Free glucose testing camps, community walks, and diet seminars.",
    category: "General Academic Event",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "All Students and Staff",
    status: "Published",
    remarks: "Clinical Pharmacy Wing"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2026-11-19",
    endDate: "2026-11-23",
    title: "Pharmacy Week Celebration",
    description: "Pharma quiz, model making, sports, and technical presentations.",
    category: "General Academic Event",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "All Students",
    status: "Published",
    remarks: "Institutional Event"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2026-11-18",
    endDate: "2026-11-24",
    title: "World Antibiotic Awareness Week",
    description: "Public seminars on combatting antimicrobial resistance (AMR).",
    category: "General Academic Event",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "All Students and Faculty",
    status: "Published",
    remarks: "Pharmacology Dept"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2026-11-19",
    endDate: "2026-11-19",
    title: "Gender Sensitivity Programme-02",
    description: "Interactive training regarding workplace professionalism and respect.",
    category: "General Academic Event",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "All Students and Staff",
    status: "Published",
    remarks: "ICC Cell"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2026-11-25",
    endDate: "2026-11-25",
    title: "Internal Committee Programme -02",
    description: "Quarterly review and safety compliance assessment session.",
    category: "General Academic Event",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "All Members",
    status: "Published",
    remarks: "ICC Cell"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2026-11-27",
    endDate: "2026-11-27",
    title: "UHV - Outreach activity",
    description: "Universal Human Values village visit and community support drive.",
    category: "General Academic Event",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "All Students and Faculty",
    status: "Published",
    remarks: "UHV Cell"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2026-12-01",
    endDate: "2026-12-01",
    title: "World AIDS Day",
    description: "Red ribbon campaigns, public awareness stalls, and clinical lectures.",
    category: "General Academic Event",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "All Students and Faculty",
    status: "Published",
    remarks: "RRC Unit"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2026-12-04",
    endDate: "2026-12-04",
    title: "Continuing Pharmacy Education -04",
    description: "Lectures on modern nanotechnology in target delivery.",
    category: "Seminar",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "All Students and Faculty",
    status: "Published",
    remarks: "CPE Committee"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2026-12-10",
    endDate: "2026-12-10",
    title: "World Kidney Day",
    description: "Diagnostic urine-analysis camps and metabolic disorder seminars.",
    category: "General Academic Event",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "All Students",
    status: "Published",
    remarks: "Clinical Pharmacy Wing"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2027-01-07",
    endDate: "2027-01-07",
    title: "Continuing Pharmacy Education -05",
    description: "Focus on AI-guided drug design and computational molecular docking.",
    category: "Seminar",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "All Students and Faculty",
    status: "Published",
    remarks: "CPE Committee"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2027-01-22",
    endDate: "2027-01-22",
    title: "Alumni Lecture 04",
    description: "Insights regarding modern pharmacovigilance careers in multinational companies.",
    category: "Guest Lecture",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "B.Pharm & Pharm.D Final Years",
    status: "Published",
    remarks: "Placement Cell series"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2027-01-11",
    endDate: "2027-01-17",
    title: "Road Safety Week",
    description: "First aid mock drills and institutional awareness rallies.",
    category: "General Academic Event",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "All Students",
    status: "Published",
    remarks: "NSS Unit"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2027-02-10",
    endDate: "2027-02-10",
    title: "Internal Committee Programme -03",
    description: "Equity guidelines review and institutional harmony discussions.",
    category: "General Academic Event",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "All Students",
    status: "Published",
    remarks: "ICC Cell"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2027-02-10",
    endDate: "2027-02-10",
    title: "World Epilepsy Day",
    description: "Neurological health screening and diagnostic update seminars.",
    category: "General Academic Event",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "Pharm.D Students",
    status: "Published",
    remarks: "Hospital Pharmacy Dept"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2027-02-11",
    endDate: "2027-02-12",
    title: "International Conference on \"AI-Powered Innovations in Drug Discovery and Development\"",
    description: "Two-day international conference featuring world-renowned AI-pharmacology speakers.",
    category: "Conference",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "All Students, Scholars and Faculty",
    status: "Published",
    remarks: "Annual Major Event"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2027-02-19",
    endDate: "2027-02-19",
    title: "CPE on Pharmaceutical Analysis",
    description: "CPE module specializing in chromatographic resolution and mass spec methods.",
    category: "Seminar",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "All Students and Faculty",
    status: "Published",
    remarks: "CPE Committee"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2027-02-23",
    endDate: "2027-02-23",
    title: "Workshop on Human Values and Professional Ethics",
    description: "Interactive session establishing standard workplace harmony and code of conduct.",
    category: "Workshop",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "All Staff and Students",
    status: "Published",
    remarks: "UHV Cell"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2027-03-04",
    endDate: "2027-03-04",
    title: "Internal Committee Programme -04",
    description: "End of term safety and harmony audits.",
    category: "General Academic Event",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "All Members",
    status: "Published",
    remarks: "ICC Cell"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2027-03-04",
    endDate: "2027-03-04",
    title: "World Obesity Day",
    description: "Metabolic assessment campaigns, BMI tracking, and public health talks.",
    category: "General Academic Event",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "All Students and Faculty",
    status: "Published",
    remarks: "Clinical Pharmacy Wing"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2027-03-06",
    endDate: "2027-03-06",
    title: "Pharma Anveshan 2027",
    description: "State level student research symposium and model design contests.",
    category: "Conference",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "All Students and Research Scholars",
    status: "Published",
    remarks: "Major Student Event"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2027-03-12",
    endDate: "2027-03-12",
    title: "Gender Sensitivity Programme -03",
    description: "Final term equity compliance seminars.",
    category: "General Academic Event",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "All Students and Staff",
    status: "Published",
    remarks: "ICC Cell"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2027-03-24",
    endDate: "2027-03-24",
    title: "World Tuberculosis Day",
    description: "DOTS awareness drives, healthcare charts distribution, and expert talks.",
    category: "General Academic Event",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "All Students",
    status: "Published",
    remarks: "Community Pharmacy Team"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2027-03-12",
    endDate: "2027-03-12",
    title: "Continuing Pharmacy Education-06",
    description: "Final CPE module on regulatory documentation and safety standards.",
    category: "Seminar",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "All Students and Faculty",
    status: "Published",
    remarks: "CPE Committee"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2027-04-01",
    endDate: "2027-04-30",
    title: "Basic Computer Skill Development for Non-Teaching Staff",
    description: "Month-long basic computing, Excel database management, and office automation training.",
    category: "Workshop",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "All Non-Teaching and Lab Staff",
    status: "Published",
    remarks: "Skill Center Initiative"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2027-05-17",
    endDate: "2027-05-17",
    title: "World Hypertension Day",
    description: "Diagnostic blood pressure checks and dietary advisory booths.",
    category: "General Academic Event",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "All Students and Staff",
    status: "Published",
    remarks: "Clinical Pharmacy Wing"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2027-05-31",
    endDate: "2027-05-31",
    title: "World NO Tobacco Day",
    description: "Awareness poster designs, patient counseling briefs, and de-addiction pamphlets.",
    category: "General Academic Event",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "All Students and Staff",
    status: "Published",
    remarks: "Hospital Pharmacy Wing"
  },

  // ==================== B.PHARM SCHEDULES (PAGE 20) ====================
  // Sem 3, 5, 7
  {
    academicYear: "2026-2027",
    programme: "B.Pharm",
    regulation: "PCI 2017",
    semester: "Semester V",
    startDate: "2026-06-15",
    endDate: "2026-06-15",
    title: "Commencement of Classes (Sem III, V, VII B.Pharm & M.Pharm)",
    description: "Official start of academic sessions for B.Pharm and M.Pharm odd semesters.",
    category: "Academic Milestone",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "B.Pharm (Sem III,V,VII), M.Pharm (Sem III)",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "B.Pharm",
    regulation: "PCI 2017",
    semester: "Semester V",
    startDate: "2026-08-03",
    endDate: "2026-08-07",
    title: "CIA I Practical Examinations",
    description: "First Continuous Internal Assessment practical examination for odd semesters.",
    category: "Practical Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "B.Pharm (Sem III,V,VII) Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "B.Pharm",
    regulation: "PCI 2017",
    semester: "Semester V",
    startDate: "2026-08-10",
    endDate: "2026-08-14",
    title: "CIA I Theory Examinations",
    description: "First Continuous Internal Assessment theory sessional examination for odd semesters.",
    category: "CIA / Sessional Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "B.Pharm (Sem III,V,VII) Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "B.Pharm",
    regulation: "PCI 2017",
    semester: "Semester V",
    startDate: "2026-10-05",
    endDate: "2026-10-09",
    title: "CIA II Practical Examinations",
    description: "Second Continuous Internal Assessment practical examination for odd semesters.",
    category: "Practical Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "B.Pharm (Sem III,V,VII) Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "B.Pharm",
    regulation: "PCI 2017",
    semester: "Semester V",
    startDate: "2026-10-12",
    endDate: "2026-10-16",
    title: "CIA II Theory Examinations",
    description: "Second Continuous Internal Assessment theory sessional examination for odd semesters.",
    category: "CIA / Sessional Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "B.Pharm (Sem III,V,VII) Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "B.Pharm",
    regulation: "PCI 2017",
    semester: "Semester V",
    startDate: "2026-11-13",
    endDate: "2026-11-13",
    title: "Last Working Day / Odd Semester Closure",
    description: "Last working day for Semesters III, V, VII odd semester B.Pharm courses (108 working days).",
    category: "Academic Milestone",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "B.Pharm (Sem III,V,VII) Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "B.Pharm",
    regulation: "PCI 2017",
    semester: "Semester V",
    startDate: "2026-10-26",
    endDate: "2026-11-06",
    title: "University Practical End-Semester Examinations",
    description: "University end-semester practical examinations conducted by SRM University.",
    category: "Practical Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "All Odd Semester Students",
    status: "Published",
    remarks: "University Examinations"
  },
  {
    academicYear: "2026-2027",
    programme: "B.Pharm",
    regulation: "PCI 2017",
    semester: "Semester V",
    startDate: "2026-11-09",
    endDate: "2026-11-20",
    title: "University Theory End-Semester Examinations",
    description: "University end-semester theory examinations conducted by SRM University.",
    category: "University Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "All Odd Semester Students",
    status: "Published",
    remarks: "University Examinations"
  },

  // Sem 4, 6, 8
  {
    academicYear: "2026-2027",
    programme: "B.Pharm",
    regulation: "PCI 2017",
    semester: "Semester VI",
    startDate: "2026-11-16",
    endDate: "2026-11-16",
    title: "Commencement of Classes (Even Semesters)",
    description: "Official start of academic sessions for B.Pharm and M.Pharm even semesters.",
    category: "Academic Milestone",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "B.Pharm (Sem IV,VI,VIII), M.Pharm (Sem II) Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "B.Pharm",
    regulation: "PCI 2017",
    semester: "Semester VI",
    startDate: "2027-01-18",
    endDate: "2027-01-22",
    title: "CIA I Practical Examinations (Even Sems)",
    description: "First Continuous Internal Assessment practical examination for even semesters.",
    category: "Practical Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "Even Semester B.Pharm Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "B.Pharm",
    regulation: "PCI 2017",
    semester: "Semester VI",
    startDate: "2027-01-25",
    endDate: "2027-01-29",
    title: "CIA I Theory Examinations (Even Sems)",
    description: "First Continuous Internal Assessment theory sessional examination for even semesters.",
    category: "CIA / Sessional Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "Even Semester B.Pharm Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "B.Pharm",
    regulation: "PCI 2017",
    semester: "Semester VI",
    startDate: "2027-03-22",
    endDate: "2027-03-26",
    title: "CIA II Practical Examinations (Even Sems)",
    description: "Second Continuous Internal Assessment practical examination for even semesters.",
    category: "Practical Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "Even Semester B.Pharm Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "B.Pharm",
    regulation: "PCI 2017",
    semester: "Semester VI",
    startDate: "2027-03-29",
    endDate: "2027-04-02",
    title: "CIA II Theory Examinations (Even Sems)",
    description: "Second Continuous Internal Assessment theory sessional examination for even semesters.",
    category: "CIA / Sessional Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "Even Semester B.Pharm Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "B.Pharm",
    regulation: "PCI 2017",
    semester: "Semester VI",
    startDate: "2027-05-07",
    endDate: "2027-05-07",
    title: "Last Working Day / Even Semester Closure",
    description: "Last working day for Semesters IV, VI, VIII even semester B.Pharm courses (112 working days).",
    category: "Academic Milestone",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "B.Pharm (Sem IV,VI,VIII) Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "B.Pharm",
    regulation: "PCI 2017",
    semester: "Semester VI",
    startDate: "2027-04-19",
    endDate: "2027-04-23",
    title: "University Practical End-Semester Examinations (Even Sems)",
    description: "University end-semester practical examinations for even semesters conducted by SRM University.",
    category: "Practical Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "All Even Semester Students",
    status: "Published",
    remarks: "University Examinations"
  },
  {
    academicYear: "2026-2027",
    programme: "B.Pharm",
    regulation: "PCI 2017",
    semester: "Semester VI",
    startDate: "2027-04-26",
    endDate: "2027-05-07",
    title: "University Theory End-Semester Examinations (Even Sems)",
    description: "University end-semester theory examinations for even semesters conducted by SRM University.",
    category: "University Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "All Even Semester Students",
    status: "Published",
    remarks: "University Examinations"
  },

  // Sem 2
  {
    academicYear: "2026-2027",
    programme: "B.Pharm",
    regulation: "PCI 2017",
    semester: "Semester II",
    startDate: "2027-03-01",
    endDate: "2027-03-01",
    title: "Commencement of Classes (Semester II)",
    description: "Official start of classes for Semester II B.Pharm and M.Pharm.",
    category: "Academic Milestone",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "B.Pharm & M.Pharm Sem II Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "B.Pharm",
    regulation: "PCI 2017",
    semester: "Semester II",
    startDate: "2027-04-29",
    endDate: "2027-05-05",
    title: "CIA I Practical Examinations (Sem II)",
    description: "First Continuous Internal Assessment practical examination for Semester II.",
    category: "Practical Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "Semester II Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "B.Pharm",
    regulation: "PCI 2017",
    semester: "Semester II",
    startDate: "2027-05-07",
    endDate: "2027-05-12",
    title: "CIA I Theory Examinations (Sem II)",
    description: "First Continuous Internal Assessment theory sessional examination for Semester II.",
    category: "CIA / Sessional Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "Semester II Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "B.Pharm",
    regulation: "PCI 2017",
    semester: "Semester II",
    startDate: "2027-07-12",
    endDate: "2027-07-16",
    title: "CIA II Practical Examinations (Sem II)",
    description: "Second Continuous Internal Assessment practical examination for Semester II.",
    category: "Practical Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "Semester II Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "B.Pharm",
    regulation: "PCI 2017",
    semester: "Semester II",
    startDate: "2027-07-20",
    endDate: "2027-07-24",
    title: "CIA II Theory Examinations (Sem II)",
    description: "Second Continuous Internal Assessment theory sessional examination for Semester II.",
    category: "CIA / Sessional Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "Semester II Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "B.Pharm",
    regulation: "PCI 2017",
    semester: "Semester II",
    startDate: "2027-08-20",
    endDate: "2027-08-20",
    title: "Last Working Day / Semester II Closure",
    description: "Last working day for Semester II B.Pharm courses (105 working days).",
    category: "Academic Milestone",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "Semester II Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "B.Pharm",
    regulation: "PCI 2017",
    semester: "Semester II",
    startDate: "2027-08-02",
    endDate: "2027-08-06",
    title: "University Practical End-Semester Examinations (Sem II)",
    description: "University end-semester practical examinations for Semester II.",
    category: "Practical Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "Semester II Students",
    status: "Published",
    remarks: "University Examinations"
  },
  {
    academicYear: "2026-2027",
    programme: "B.Pharm",
    regulation: "PCI 2017",
    semester: "Semester II",
    startDate: "2027-08-09",
    endDate: "2027-08-19",
    title: "University Theory End-Semester Examinations (Sem II)",
    description: "University end-semester theory examinations for Semester II.",
    category: "University Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "Semester II Students",
    status: "Published",
    remarks: "University Examinations"
  },

  // Sem 1
  {
    academicYear: "2026-2027",
    programme: "B.Pharm",
    regulation: "PCI 2017",
    semester: "Semester I",
    startDate: "2026-09-02",
    endDate: "2026-09-02",
    title: "Commencement of Classes (Semester I)",
    description: "Official start of classes for Semester I B.Pharm, M.Pharm, and Pharm.D.",
    category: "Academic Milestone",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "First Semester B.Pharm & M.Pharm Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "B.Pharm",
    regulation: "PCI 2017",
    semester: "Semester I",
    startDate: "2026-11-02",
    endDate: "2026-11-06",
    title: "CIA I Practical Examinations (Sem I)",
    description: "First Continuous Internal Assessment practical examination for Semester I.",
    category: "Practical Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "Semester I Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "B.Pharm",
    regulation: "PCI 2017",
    semester: "Semester I",
    startDate: "2026-11-10",
    endDate: "2026-11-14",
    title: "CIA I Theory Examinations (Sem I)",
    description: "First Continuous Internal Assessment theory sessional examination for Semester I.",
    category: "CIA / Sessional Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "Semester I Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "B.Pharm",
    regulation: "PCI 2017",
    semester: "Semester I",
    startDate: "2027-01-05",
    endDate: "2027-01-09",
    title: "CIA II Practical Examinations (Sem I)",
    description: "Second Continuous Internal Assessment practical examination for Semester I.",
    category: "Practical Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "Semester I Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "B.Pharm",
    regulation: "PCI 2017",
    semester: "Semester I",
    startDate: "2027-01-18",
    endDate: "2027-01-22",
    title: "CIA II Theory Examinations (Sem I)",
    description: "Second Continuous Internal Assessment theory sessional examination for Semester I.",
    category: "CIA / Sessional Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "Semester I Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "B.Pharm",
    regulation: "PCI 2017",
    semester: "Semester I",
    startDate: "2027-02-17",
    endDate: "2027-02-17",
    title: "Last Working Day / Semester I Closure",
    description: "Last working day for Semester I B.Pharm courses (108 working days).",
    category: "Academic Milestone",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "Semester I Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "B.Pharm",
    regulation: "PCI 2017",
    semester: "Semester I",
    startDate: "2027-02-01",
    endDate: "2027-02-05",
    title: "University Practical End-Semester Examinations (Sem I)",
    description: "University end-semester practical examinations for Semester I.",
    category: "Practical Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "Semester I Students",
    status: "Published",
    remarks: "University Examinations"
  },
  {
    academicYear: "2026-2027",
    programme: "B.Pharm",
    regulation: "PCI 2017",
    semester: "Semester I",
    startDate: "2027-02-08",
    endDate: "2027-02-17",
    title: "University Theory End-Semester Examinations (Sem I)",
    description: "University end-semester theory examinations for Semester I.",
    category: "University Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "Semester I Students",
    status: "Published",
    remarks: "University Examinations"
  },

  // ==================== M.PHARM SCHEDULES (PAGE 21) ====================
  // Sem 1 (Mostly matches B.Pharm Sem 1 except end date)
  {
    academicYear: "2026-2027",
    programme: "M.Pharm",
    regulation: "PCI 2020",
    semester: "Semester I",
    startDate: "2026-09-02",
    endDate: "2026-09-02",
    title: "Commencement of Classes (M.Pharm Semester I)",
    description: "Official start of classes for M.Pharm Semester I.",
    category: "Academic Milestone",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "First Semester M.Pharm Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "M.Pharm",
    regulation: "PCI 2020",
    semester: "Semester I",
    startDate: "2026-11-02",
    endDate: "2026-11-06",
    title: "CIA I Practical Examinations (M.Pharm Sem I)",
    description: "First Continuous Internal Assessment practical examination for M.Pharm Semester I.",
    category: "Practical Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "M.Pharm Semester I Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "M.Pharm",
    regulation: "PCI 2020",
    semester: "Semester I",
    startDate: "2026-11-10",
    endDate: "2026-11-14",
    title: "CIA I Theory Examinations (M.Pharm Sem I)",
    description: "First Continuous Internal Assessment theory sessional examination for M.Pharm Semester I.",
    category: "CIA / Sessional Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "M.Pharm Semester I Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "M.Pharm",
    regulation: "PCI 2020",
    semester: "Semester I",
    startDate: "2027-01-05",
    endDate: "2027-01-09",
    title: "CIA II Practical Examinations (M.Pharm Sem I)",
    description: "Second Continuous Internal Assessment practical examination for M.Pharm Semester I.",
    category: "Practical Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "M.Pharm Semester I Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "M.Pharm",
    regulation: "PCI 2020",
    semester: "Semester I",
    startDate: "2027-01-18",
    endDate: "2027-01-22",
    title: "CIA II Theory Examinations (M.Pharm Sem I)",
    description: "Second Continuous Internal Assessment theory sessional examination for M.Pharm Semester I.",
    category: "CIA / Sessional Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "M.Pharm Semester I Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "M.Pharm",
    regulation: "PCI 2020",
    semester: "Semester I",
    startDate: "2027-02-10",
    endDate: "2027-02-10",
    title: "Last Working Day / M.Pharm Semester I Closure",
    description: "Last working day for M.Pharm Semester I courses (103 working days).",
    category: "Academic Milestone",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "M.Pharm Semester I Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "M.Pharm",
    regulation: "PCI 2020",
    semester: "Semester I",
    startDate: "2027-02-10",
    endDate: "2027-02-12",
    title: "University Practical End-Semester Examinations (M.Pharm Sem I)",
    description: "University end-semester practical examinations for M.Pharm Semester I.",
    category: "Practical Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "M.Pharm Semester I Students",
    status: "Published",
    remarks: "University Examinations"
  },
  {
    academicYear: "2026-2027",
    programme: "M.Pharm",
    regulation: "PCI 2020",
    semester: "Semester I",
    startDate: "2027-02-01",
    endDate: "2027-02-05",
    title: "University Theory End-Semester Examinations (M.Pharm Sem I)",
    description: "University end-semester theory examinations for M.Pharm Semester I.",
    category: "University Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "M.Pharm Semester I Students",
    status: "Published",
    remarks: "University Examinations"
  },

  // Sem 2
  {
    academicYear: "2026-2027",
    programme: "M.Pharm",
    regulation: "PCI 2020",
    semester: "Semester II",
    startDate: "2027-03-01",
    endDate: "2027-03-01",
    title: "Commencement of Classes (M.Pharm Semester II)",
    description: "Official start of classes for Semester II M.Pharm.",
    category: "Academic Milestone",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "M.Pharm Semester II Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "M.Pharm",
    regulation: "PCI 2020",
    semester: "Semester II",
    startDate: "2027-04-29",
    endDate: "2027-05-05",
    title: "CIA I Practical Examinations (M.Pharm Sem II)",
    description: "First Continuous Internal Assessment practical examination for M.Pharm Semester II.",
    category: "Practical Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "M.Pharm Semester II Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "M.Pharm",
    regulation: "PCI 2020",
    semester: "Semester II",
    startDate: "2027-05-07",
    endDate: "2027-05-12",
    title: "CIA I Theory Examinations (M.Pharm Sem II)",
    description: "First Continuous Internal Assessment theory sessional examination for M.Pharm Semester II.",
    category: "CIA / Sessional Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "M.Pharm Semester II Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "M.Pharm",
    regulation: "PCI 2020",
    semester: "Semester II",
    startDate: "2027-07-12",
    endDate: "2027-07-16",
    title: "CIA II Practical Examinations (M.Pharm Sem II)",
    description: "Second Continuous Internal Assessment practical examination for M.Pharm Semester II.",
    category: "Practical Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "M.Pharm Semester II Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "M.Pharm",
    regulation: "PCI 2020",
    semester: "Semester II",
    startDate: "2027-07-20",
    endDate: "2027-07-24",
    title: "CIA II Theory Examinations (M.Pharm Sem II)",
    description: "Second Continuous Internal Assessment theory sessional examination for M.Pharm Semester II.",
    category: "CIA / Sessional Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "M.Pharm Semester II Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "M.Pharm",
    regulation: "PCI 2020",
    semester: "Semester II",
    startDate: "2027-08-13",
    endDate: "2027-08-13",
    title: "Last Working Day / M.Pharm Semester II Closure",
    description: "Last working day for M.Pharm Semester II courses (100 working days).",
    category: "Academic Milestone",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "M.Pharm Semester II Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "M.Pharm",
    regulation: "PCI 2020",
    semester: "Semester II",
    startDate: "2027-08-13",
    endDate: "2027-08-16",
    title: "University Practical End-Semester Examinations (M.Pharm Sem II)",
    description: "University end-semester practical examinations for M.Pharm Semester II.",
    category: "Practical Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "M.Pharm Semester II Students",
    status: "Published",
    remarks: "University Examinations"
  },
  {
    academicYear: "2026-2027",
    programme: "M.Pharm",
    regulation: "PCI 2020",
    semester: "Semester II",
    startDate: "2027-08-04",
    endDate: "2027-08-08",
    title: "University Theory End-Semester Examinations (M.Pharm Sem II)",
    description: "University end-semester theory examinations for M.Pharm Semester II.",
    category: "University Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "M.Pharm Semester II Students",
    status: "Published",
    remarks: "University Examinations"
  },

  // Sem 3
  {
    academicYear: "2026-2027",
    programme: "M.Pharm",
    regulation: "PCI 2020",
    semester: "Semester III",
    startDate: "2026-06-15",
    endDate: "2026-06-15",
    title: "Commencement of Classes (M.Pharm Semester III)",
    description: "Official start of classes for M.Pharm Semester III.",
    category: "Academic Milestone",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "Third Semester M.Pharm Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "M.Pharm",
    regulation: "PCI 2020",
    semester: "Semester III",
    startDate: "2026-08-11",
    endDate: "2026-08-11",
    title: "I Sessional Theory Exam (M.Pharm Sem III)",
    description: "First Non-University sessional theory examination.",
    category: "CIA / Sessional Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "Third Semester M.Pharm Students",
    status: "Published",
    remarks: "Non-University Exam"
  },
  {
    academicYear: "2026-2027",
    programme: "M.Pharm",
    regulation: "PCI 2020",
    semester: "Semester III",
    startDate: "2026-09-11",
    endDate: "2026-09-11",
    title: "II Sessional Theory Exam (M.Pharm Sem III)",
    description: "Second Non-University sessional theory examination.",
    category: "CIA / Sessional Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "Third Semester M.Pharm Students",
    status: "Published",
    remarks: "Non-University Exam"
  },
  {
    academicYear: "2026-2027",
    programme: "M.Pharm",
    regulation: "PCI 2020",
    semester: "Semester III",
    startDate: "2026-09-17",
    endDate: "2026-09-17",
    title: "M.Pharm Semester III Closure",
    description: "Official end of Semester III research milestones for M.Pharm.",
    category: "Academic Milestone",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "Third Semester M.Pharm Students",
    status: "Published"
  },

  // ==================== PHARM.D SCHEDULES (PAGE 22) ====================
  // II-V Year, PB II-III Year
  {
    academicYear: "2026-2027",
    programme: "Pharm.D",
    regulation: "PCI 2008",
    semester: "Year II",
    startDate: "2026-06-15",
    endDate: "2026-06-15",
    title: "Commencement of Classes (Pharm.D Year II-V & PB Yr II-III)",
    description: "Official start of academic year classes for annual Pharm.D batches.",
    category: "Academic Milestone",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "Pharm.D (Yr II-V) & PB (Yr II-III) Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "Pharm.D",
    regulation: "PCI 2008",
    semester: "Year II",
    startDate: "2026-08-31",
    endDate: "2026-09-05",
    title: "First Sessional Practical Examinations (Pharm.D Yr II-V)",
    description: "First internal assessment sessional practical examination.",
    category: "Practical Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "Pharm.D (Yr II-V) Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "Pharm.D",
    regulation: "PCI 2008",
    semester: "Year II",
    startDate: "2026-09-07",
    endDate: "2026-09-12",
    title: "First Sessional Theory Examinations (Pharm.D Yr II-V)",
    description: "First internal assessment sessional theory examination.",
    category: "CIA / Sessional Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "Pharm.D (Yr II-V) Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "Pharm.D",
    regulation: "PCI 2008",
    semester: "Year II",
    startDate: "2026-11-30",
    endDate: "2026-12-05",
    title: "Second Sessional Practical Examinations (Pharm.D Yr II-V)",
    description: "Second internal assessment sessional practical examination.",
    category: "Practical Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "Pharm.D (Yr II-V) Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "Pharm.D",
    regulation: "PCI 2008",
    semester: "Year II",
    startDate: "2026-12-07",
    endDate: "2026-12-12",
    title: "Second Sessional Theory Examinations (Pharm.D Yr II-V)",
    description: "Second internal assessment sessional theory examination.",
    category: "CIA / Sessional Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "Pharm.D (Yr II-V) Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "Pharm.D",
    regulation: "PCI 2008",
    semester: "Year II",
    startDate: "2027-03-08",
    endDate: "2027-03-13",
    title: "Third Sessional Practical Examinations (Pharm.D Yr II-V)",
    description: "Third internal assessment sessional practical examination.",
    category: "Practical Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "Pharm.D (Yr II-V) Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "Pharm.D",
    regulation: "PCI 2008",
    semester: "Year II",
    startDate: "2027-03-15",
    endDate: "2027-03-20",
    title: "Third Sessional Theory Examinations (Pharm.D Yr II-V)",
    description: "Third internal assessment sessional theory examination.",
    category: "CIA / Sessional Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "Pharm.D (Yr II-V) Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "Pharm.D",
    regulation: "PCI 2008",
    semester: "Year II",
    startDate: "2027-05-07",
    endDate: "2027-05-07",
    title: "Pharm.D Year II-V Academic Year Closure",
    description: "Official last working day for annual Pharm.D courses (220 working days).",
    category: "Academic Milestone",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "Pharm.D (Yr II-V) Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "Pharm.D",
    regulation: "PCI 2008",
    semester: "Year II",
    startDate: "2027-04-19",
    endDate: "2027-04-30",
    title: "Annual University Theory Examinations (Pharm.D Yr II-V)",
    description: "University annual comprehensive theory examinations.",
    category: "University Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "Pharm.D (Yr II-V) Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "Pharm.D",
    regulation: "PCI 2008",
    semester: "Year II",
    startDate: "2027-05-03",
    endDate: "2027-05-07",
    title: "Annual University Practical Examinations (Pharm.D Yr II-V)",
    description: "University annual comprehensive practical examinations.",
    category: "Practical Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "Pharm.D (Yr II-V) Students",
    status: "Published"
  },

  // Pharm.D Year I & PB Year I
  {
    academicYear: "2026-2027",
    programme: "Pharm.D",
    regulation: "PCI 2008",
    semester: "Year I",
    startDate: "2026-09-02",
    endDate: "2026-09-02",
    title: "Commencement of Classes (Pharm.D Year I & PB Year I)",
    description: "Official start of academic year classes for annual Pharm.D First Year.",
    category: "Academic Milestone",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "Pharm.D Yr I & PB Yr I Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "Pharm.D",
    regulation: "PCI 2008",
    semester: "Year I",
    startDate: "2026-11-30",
    endDate: "2026-12-05",
    title: "First Sessional Practical Examinations (Pharm.D Yr I)",
    description: "First internal sessional practical examinations.",
    category: "Practical Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "Pharm.D Yr I & PB Yr I Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "Pharm.D",
    regulation: "PCI 2008",
    semester: "Year I",
    startDate: "2026-12-07",
    endDate: "2026-12-12",
    title: "First Sessional Theory Examinations (Pharm.D Yr I)",
    description: "First internal sessional theory examinations.",
    category: "CIA / Sessional Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "Pharm.D Yr I & PB Yr I Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "Pharm.D",
    regulation: "PCI 2008",
    semester: "Year I",
    startDate: "2027-03-08",
    endDate: "2027-03-13",
    title: "Second Sessional Practical Examinations (Pharm.D Yr I)",
    description: "Second internal sessional practical examinations.",
    category: "Practical Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "Pharm.D Yr I & PB Yr I Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "Pharm.D",
    regulation: "PCI 2008",
    semester: "Year I",
    startDate: "2027-03-17",
    endDate: "2027-03-22",
    title: "Second Sessional Theory Examinations (Pharm.D Yr I)",
    description: "Second internal sessional theory examinations.",
    category: "CIA / Sessional Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "Pharm.D Yr I & PB Yr I Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "Pharm.D",
    regulation: "PCI 2008",
    semester: "Year I",
    startDate: "2027-07-12",
    endDate: "2027-07-16",
    title: "Third Sessional Practical Examinations (Pharm.D Yr I)",
    description: "Third internal sessional practical examinations.",
    category: "Practical Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "Pharm.D Yr I & PB Yr I Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "Pharm.D",
    regulation: "PCI 2008",
    semester: "Year I",
    startDate: "2027-07-20",
    endDate: "2027-07-24",
    title: "Third Sessional Theory Examinations (Pharm.D Yr I)",
    description: "Third internal sessional theory examinations.",
    category: "CIA / Sessional Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "Pharm.D Yr I & PB Yr I Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "Pharm.D",
    regulation: "PCI 2008",
    semester: "Year I",
    startDate: "2027-08-27",
    endDate: "2027-08-27",
    title: "Pharm.D Year I Academic Year Closure",
    description: "Official last working day for Pharm.D Year I (225 working days).",
    category: "Academic Milestone",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "Pharm.D Yr I & PB Yr I Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "Pharm.D",
    regulation: "PCI 2008",
    semester: "Year I",
    startDate: "2027-08-09",
    endDate: "2027-08-20",
    title: "Annual University Theory Examinations (Pharm.D Yr I)",
    description: "University annual comprehensive theory examinations.",
    category: "University Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "Pharm.D Yr I & PB Yr I Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "Pharm.D",
    regulation: "PCI 2008",
    semester: "Year I",
    startDate: "2027-08-23",
    endDate: "2027-08-27",
    title: "Annual University Practical Examinations (Pharm.D Yr I)",
    description: "University annual comprehensive practical examinations.",
    category: "Practical Examination",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "Pharm.D Yr I & PB Yr I Students",
    status: "Published"
  },

  // ==================== INSTITUTION VACATIONS / OTHER ====================
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2027-06-01",
    endDate: "2027-06-30",
    title: "Summer Vacation Period",
    description: "Official summer holidays block for all institutional courses.",
    category: "Vacation",
    workingDay: "No",
    holiday: "Yes",
    applicableTo: "All Students and Faculty",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "B.Pharm",
    regulation: "PCI 2017",
    semester: "Semester VII",
    startDate: "2027-07-01",
    endDate: "2027-07-01",
    title: "Commencement of Classes (Odd Semesters 2027-2028)",
    description: "Commencement of classes for new academic year's odd semesters.",
    category: "Academic Milestone",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "B.Pharm (Sem III,V,VII) Students",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2027-07-12",
    endDate: "2027-07-16",
    title: "FDP on Advances in Drug Delivery Systems",
    description: "5-day Faculty Development Programme focusing on modern nano-carriers.",
    category: "FDP",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "All Faculty and PhD Scholars",
    status: "Published"
  },
  {
    academicYear: "2026-2027",
    programme: "Institution",
    regulation: "Institution",
    semester: "All",
    startDate: "2027-07-20",
    endDate: "2027-07-20",
    title: "Orientation for New Admissions batch (2027-2028)",
    description: "General orientation and induction for freshers of B.Pharm and Pharm.D.",
    category: "Orientation",
    workingDay: "Yes",
    holiday: "No",
    applicableTo: "First Year Students and Parents",
    status: "Published"
  }
];

async function main() {
  console.log(`Starting PDF Academic Calendar Import. Total parsed events: ${pdfEvents.length}`);

  let upserts = 0;
  for (const event of pdfEvents) {
    const id = generateDeterministicEventId(event);
    const docRef = doc(db, 'academicCalendar', id);
    await setDoc(docRef, {
      ...event,
      id,
      updatedAt: new Date().toISOString()
    }, { merge: true });
    upserts++;
  }

  console.log(`Successfully completed upsert for ${upserts} events to /academicCalendar collection.`);

  // Query and print statistics per month
  console.log("\n--- FIRESTORE RECORD STATISTICS PER MONTH ---");
  const colRef = collection(db, 'academicCalendar');
  const snap = await getDocs(colRef);
  
  const monthCounts: Record<string, number> = {
    "2026-06": 0,
    "2026-07": 0,
    "2026-08": 0,
    "2026-09": 0,
    "2026-10": 0,
    "2026-11": 0,
    "2026-12": 0,
    "2027-01": 0,
    "2027-02": 0,
    "2027-03": 0,
    "2027-04": 0,
    "2027-05": 0,
    "2027-06": 0,
    "2027-07": 0,
    "2027-08": 0,
  };

  snap.forEach((docSnap) => {
    const data = docSnap.data();
    const startDate = data.startDate; // YYYY-MM-DD
    if (startDate && typeof startDate === 'string') {
      const monthKey = startDate.substring(0, 7); // YYYY-MM
      if (monthCounts[monthKey] !== undefined) {
        monthCounts[monthKey]++;
      } else {
        // also keep track if any other months exist
        monthCounts[monthKey] = 1;
      }
    }
  });

  const monthsToReport = [
    "2026-06", "2026-07", "2026-08", "2026-09", "2026-10", "2026-11", "2026-12",
    "2027-01", "2027-02", "2027-03", "2027-04", "2027-05", "2027-06", "2027-07", "2027-08"
  ];

  monthsToReport.forEach((m) => {
    console.log(`${m}: ${monthCounts[m] || 0} events`);
  });
}

main().catch(err => {
  console.error("Migration error:", err);
  process.exit(1);
});
